### PR TITLE
ENH Add silverstripe/doorman

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/.github/issues/350

~Needs https://github.com/silverstripe/supported-modules/pull/49 merged before CI will work~

### CODE REVIEW

**Comment by GuySartorelli** [comment]
> Needs https://github.com/silverstripe/supported-modules/pull/49 merged before CI will work

This is #49... did you mean to put that note in https://github.com/silverstripe/doorman/pull/49 instead?

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
This isn't and was never a [supported module](https://docs.silverstripe.org/en/project_governance/supported_modules/).
It cannot be in the `supportedModules` section.

Please move it to "misc"

**Comment by emteknetnz** [comment]
Have moved

**Review by GuySartorelli — APPROVED** [review]
LGTM

**Pull request merged**
